### ISSUE TITLE
Useless UAC request

### ISSUE THREAD

**Issue by krypt-lynx** [OniVe/S.E.A.#1]
All in title.
Happens in SEA.CT.Unpacked

**Comment by OniVe** [comment]
Release/SEA.CT.Unpacked
Or do you mean something else?

**Comment by krypt-lynx** [comment]
Судя по описанию мода, вы говорите по-русски %)

Да, именно. Приложение по дефолту требует права администратора, хотя не делает ничего такого, для чего они действительно нужны

**Comment by OniVe** [comment]
Права администратора нужны только для быстрой регистрации по всем локальным адресам. В новой вервии прав администратора не будет запрашивать, но потребуется открыть требуемые порты заранее.
П.С. Я несколько загружен на работе, по этому вижу вопросы не сразу. Отвечаю как правило сразу же.

**Comment by krypt-lynx** [comment]
Вы открываете порты в Windows Firewall, я верно понял? Тогда в некоторых случаях этот запрос может оказаться совсем бесполезным, потому как может стоять отдельный firewall (как в моём случае, Comodo, стандартный же совсем отключён). 

Я думаю, стоит вынести запрос на открытие порта вот отдельный UAC запрос на повышение прав, а не использовать общее требование администратора в манифесте.

**Comment by OniVe** [comment]
Как я уже написал, в новой версии этого не будет. Сейчас идёт тестирование.

**Comment by OniVe** [comment]
Если интересно:
Было:
`startOptions = new StartOptions();
var hostName = System.Net.Dns.GetHostName();
startOptions.Urls.Add(string.Format("http://{0}:{1}", "localhost", port));
startOptions.Urls.Add(string.Format("http://{0}:{1}", "127.0.0.1", port));
startOptions.Urls.Add(string.Format("http://{0}:{1}", hostName, port));

foreach (System.Net.IPAddress ip in System.Net.Dns.GetHostAddresses(hostName))
{
	try
	{
		if (ip.AddressFamily == System.Net.Sockets.AddressFamily.InterNetwork)
			startOptions.Urls.Add(string.Format("http://{0}:{1}", ip.ToString(), port));
	}
	catch { }
}

Стало:

startOptions = new StartOptions();
startOptions.AppStartup = "http://*";
startOptions.Port = port;`

Стало:
`startOptions = new StartOptions();
startOptions.AppStartup = "http://+";
startOptions.Port = port;`

**Comment by OniVe** [comment]
```
//Было: (Эта не замысловатая конструкция требует прав Администратора)
startOptions = new StartOptions();
var hostName = System.Net.Dns.GetHostName();
startOptions.Urls.Add(string.Format("http://{0}:{1}", "localhost", port));
startOptions.Urls.Add(string.Format("http://{0}:{1}", "127.0.0.1", port));
startOptions.Urls.Add(string.Format("http://{0}:{1}", hostName, port));

foreach (System.Net.IPAddress ip in System.Net.Dns.GetHostAddresses(hostName))
        if (ip.AddressFamily == System.Net.Sockets.AddressFamily.InterNetwork)
            startOptions.Urls.Add(string.Format("http://{0}:{1}", ip.ToString(), port));
//Стало:

startOptions = new StartOptions();
startOptions.AppStartup = "http://+";
startOptions.Port = port;
```
